export const formStyles = {
  formContainer: {
    width: { xs: '100%', sm: '100%', md: '800px' },
    height: 'auto',
    maxHeight: { xs: '90vh', sm: '85vh', md: '80vh' },
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    overflowX: 'hidden',
    p: { xs: 2, sm: 3, md: 4 },
    backgroundColor: 'rgba(0, 41, 54, 0.9)',
    borderRadius: 2,
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    gap: { xs: 1.5, sm: 2, md: 2.5 },
    mx: 'auto',
  },
  formTitle: {
    fontSize: { xs: '24px', sm: '30px', md: '36px', lg: '42px' },
    fontFamily: 'SaiyanFont, sans-serif',
    textAlign: 'center',
    color: '#fff',
    mb: { xs: 1.5, sm: 2, md: 3 },
    mt: { xs: 1, sm: 1, md: 0 },
    textShadow: '2px 2px 0 #002936',
  },
  inputFontSize: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
  },
  inputLabel: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
    color: 'rgba(255, 255, 255, 0.9)',
  },
  input: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
    backgroundColor: 'rgba(101, 184, 203, 0.1) !important',
    color: 'white !important',
    p: 1,
    borderRadius: '4px',
    '&:hover': { backgroundColor: 'rgba(101, 184, 203, 0.2) !important' },
    '&:focus': { backgroundColor: 'rgba(101, 184, 203, 0.25) !important' },
  },
  inputFullWidth: {
    width: '100%',
  },
  inputStandardWidth: {
    width: { xs: '80%', sm: '65%', md: '50%' },
  },
  inputMediumWidth: {
    width: { xs: '100%', sm: '90%', md: '80%' },
  },
  helperText: {
    fontSize: '13px',
    color: 'rgba(255,255,255,0.8)',
    mt: 0.5,
    ml: 1,
  },
  select: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
    backgroundColor: 'rgba(101, 184, 203, 0.1) !important',
    color: 'white !important',
    borderRadius: '4px',
    p: 0.5,
    '&:hover': { backgroundColor: 'rgba(101, 184, 203, 0.2) !important' },
    '&:focus': { backgroundColor: 'rgba(101, 184, 203, 0.25) !important' },
    '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255, 255, 255, 0.3)' },
    '&.Mui-focused .MuiOutlinedInput-notchedOutline': { borderColor: '#65b8cb' },
    '& .MuiSvgIcon-root': { color: 'white' },
  },
  menuItem: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
    '&.Mui-selected': { backgroundColor: 'rgba(101, 184, 203, 0.2)' },
    '&.Mui-selected:hover': { backgroundColor: 'rgba(101, 184, 203, 0.3)' },
    '&:hover': { backgroundColor: 'rgba(101, 184, 203, 0.1)' },
  },
  formControl: {
    mb: 2,
    width: { xs: '95%', sm: '90%', md: '80%' },
  },
  submitButton: {
    backgroundColor: '#003d4d !important',
    color: 'white !important',
    '&.MuiButton-root:hover': { backgroundColor: '#00526a !important' },
    borderRadius: '4px !important',
    padding: { xs: '8px 16px !important', sm: '10px 20px !important' },
    marginTop: { xs: '15px !important', sm: '20px !important' },
    alignSelf: 'center',
    width: { xs: '80%', sm: '65%', md: '50%' },
    fontSize: { xs: '16px', sm: '17px', md: '18px' },
    fontFamily: 'SaiyanFont, sans-serif',
    textTransform: 'none',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.3) !important',
  },
  accordion: {
    width: { xs: '95%', sm: '90%', md: '80%' },
    backgroundColor: 'rgba(0, 61, 77, 0.6)',
    color: 'white',
    borderRadius: '8px !important',
    my: 2,
    mb: 3,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    '.MuiAccordionSummary-root': {
      borderRadius: '8px',
      '&:hover': { backgroundColor: 'rgba(101, 184, 203, 0.15)' },
    },
    '.MuiSvgIcon-root': { color: 'white' },
  },
  accordionTitle: {
    fontFamily: 'SaiyanFont, sans-serif',
    fontSize: '18px',
    textShadow: '1px 1px 0 #002936',
  },
  dateLabel: {
    fontSize: {
      xs: '14px!important',
      sm: '15px!important',
      md: '16px!important',
      lg: '17px!important',
    },
    color: 'rgba(255, 255, 255, 0.9)',
    mb: 1,
    ml: 1,
  },
};
